name: CI_rosco-toolbox

# We run CI on push commits on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        python-version: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install compilers
      - name: Add dependencies ubuntu specific
        if: false == contains( matrix.os, 'windows')
        run: |
          conda install -y compilers

      # Install compilers
      - name: Add dependencies ubuntu specific
        if: true == contains( matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          conda install -y m2w64-toolchain

      # Install ROSCO toolbox
      - name: Compile ROSCO
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake ..
          make install
          
